iac

diff --git a/.github/workflows/az_tf_plan.yml b/.github/workflows/az_tf_plan.yml
--- a/.github/workflows/az_tf_plan.yml
+++ b/.github/workflows/az_tf_plan.yml
@@ -57,8 +57,40 @@ jobs:
         uses: hashicorp/setup-terraform@v1.3.2
       
       - name: Az Login
-        run:
-          az login --service-principal --username $DEV_CLIENT_ID --password $DEV_CLIENT_SECRET --tenant $DEV_TENANT_ID       
+        run: |
+          echo "::group::Selecting and getting secrets"
+          if [[ -z "${TF_SECRET}" ]];
+          then
+            echo "::error::There's an issue with the secret that handles the Landing of the environment"
+            secret_exists=false
+            echo "secret_exists: $secret_exists"
+            echo ::set-output  name=secret_exists::$secret_exists
+            exit 120
+          else
+            echo "Ok. Detected existing environment secret..."
+            echo "${TF_SECRET}" > secret.json        
+            jq .tf_landing ./secret.json > landing.tfvars.json
+            # create cloud.json if secret value tf_cloud found
+            [[ $(grep tf_cloud ./secret.json|wc -l) == 1 ]] && { jq .tf_cloud ./secret.json > cloud.tfvars.json || true; }
+            secret_exists=true
+            echo "secret_exists: $secret_exists"
+            rm secret.json
+          fi
+          echo "::endgroup::"
+          echo "::group::Setting up cloud credentials"
+          export SUBSCRIPTION_ID=$(jq .azurerm_subscription_id landing.tfvars.json --raw-output) 
+          export CLIENT_ID=$(jq .azurerm_client_id landing.tfvars.json --raw-output)
+          export CLIENT_SECRET=$(jq .azurerm_client_secret landing.tfvars.json --raw-output) 
+          export TENANT_ID=$(jq .azurerm_tenant_id landing.tfvars.json --raw-output)
+          az login --service-principal --username $CLIENT_ID --password $CLIENT_SECRET --tenant $TENANT_ID || { echo "::error::Error login into Azure. Most likely there is NOT a SECRET AVAILABLE for your environment that contains your Azure credentials."; exit 199; }
+          az account set --subscription $SUBSCRIPTION_ID || { echo "::error::Error setting subscriptcion. Provide a correct subscription. Verify your Azure credentials."; exit 199; }
+          rm -fr landing.tfvars.json
+          echo "::endgroup::
+        env: 
+          TF_SECRET: ${{ secrets[github.event.inputs.environment] }}
+        shell: bash
+      
+ #         az login --service-principal --username $DEV_CLIENT_ID --password $DEV_CLIENT_SECRET --tenant $DEV_TENANT_ID       
  #         az login --allow-no-subscriptions
 
       - name: Terraform Init
