iac

diff --git a/.github/workflows/az_tf_apply.yml b/.github/workflows/az_tf_apply.yml
--- a/.github/workflows/az_tf_apply.yml
+++ b/.github/workflows/az_tf_apply.yml
@@ -85,8 +85,7 @@ jobs:
           export SUBSCRIPTION_ID=$(jq .azurerm_subscription_id landing.tfvars.json --raw-output) 
           export CLIENT_ID=$(jq .azurerm_client_id landing.tfvars.json --raw-output)
           export CLIENT_SECRET=$(jq .azurerm_client_secret landing.tfvars.json --raw-output) 
-          export TENANT_ID=$(jq .azurerm_tenant_id landing.tfvars.json --raw-output)
-          az login --service-principal --username $CLIENT_ID --password $CLIENT_SECRET --tenant $TENANT_ID || { echo "::error::Error login into Azure. Most likely there is NOT a SECRET AVAILABLE for your environment that contains your Azure credentials."; exit 199; }
+          az login --service-principal --username $CLIENT_ID --password $CLIENT_SECRET --tenant ${{ secrets.DEV_TENANT_ID }} || { echo "::error::Error login into Azure. Most likely there is NOT a SECRET AVAILABLE for your environment that contains your Azure credentials."; exit 199; }
           az account set --subscription $SUBSCRIPTION_ID || { echo "::error::Error setting subscriptcion. Provide a correct subscription. Verify your Azure credentials."; exit 199; }
           rm -fr landing.tfvars.json
           echo "::endgroup::"
